name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: heberoffice21
          svg_out_path: dist/github-contribution-grid-snake.svg
          color_snake: darkgreen # Cor da cobra
          color_dots: darkblue   # Cor dos pontos (opcional)
          background: #0d1117    # Cor de fundo do GitHub (cinza escuro)

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
